{{- if .Values.httpRoute.enabled -}}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "helm-chart.fullname" . }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
  {{- with .Values.httpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  hostnames:
    {{- range .Values.httpRoute.hosts }}
    - {{ . | quote }}
    {{- end }}
  rules:
    {{- range .Values.httpRoute.paths }}
    - matches:
        - path:
            type: Prefix
            value: {{ .path }}
      backendRefs:
        - name: {{ include "helm-chart.fullname" $ }}
          port: {{ $.Values.service.port }}
    {{- end }}
{{- end }}
